language: node_js
node_js:
- 14.18.0
script: npm run release
if: tag IS present
deploy:
  provider: releases
  api_key:
    secure: "e9G2Mz8GrLlJxcw1wU3iTGTn/7ucPyWfWkKuB/zfMCj2GkGi7hhqmimt69OFrvZP+Qg6jifgOgY7S/qfCsdHFWX2xwB/+uRQFcT0Q+49HIHFfxy80AGCRMFDTRcuC5mJICZkukPOaznqqsvACYLXP5PttEG8HMH1WdUfpvvhOQ5OoepQ6VCrQctT4wOkmu7xyO6Bm+gDOJyjheP/VwoDLou8boXNZcRyU2JsfKfeVOIc8rBhiZPIdWG+UVmxceDApQ7KVBnmZY8K6GVfQQItRqwyBfzO/K79uReNte074v9WKIz9TPtWiJIEMn/a4E0s0zScpNX4d6h7hwCO3UYBemN1GAj/+3Ww7USmOwUowmKJYQYigcF9JcheZ7SqxnA3kk/jtbaiAqjk+3FMswMUQrlCVaoPRYUPzAO9wJExnX8/oL7OuqmHosT78iZYPAwjzz32Tl8khd2L/ljCaCo+pZzX29pUHsG5TbgMH+c9fmW7bmDbbz3OObhfll7NhJDpNhbAR2lTsXbCYkVH7uC2tqyaxdb/X52Ux9HsSSFqCbj8+a51zDx/2QI8TxCt/UJ76Mc0XFsdX+FObwfZa90TsTQ2UF08bAxfWiA2PF+97zzHwic+4x5iTip/xIqTKkZZ+Y9ReF20mkN+PSuef0mMeykkg8LopYTQPWf+itOEV2k="
  file_glob: true
  file: artifacts/*
  skip_cleanup: true
  on:
    repo: artcom/topic-browser
    tags: true
