language: node_js
node_js:
  - '10.12.0'

script: npm run release

deploy:
  provider: releases
  api_key:
    secure: "Sw/kicSQ7odtZxUxbVnkBT13Jbr+bkob1D/AVGFulcSk15rcamm05t3JOlzomxCShnN7aj3uDUE8Gs6YifxzSj7MXvTwSjPcZZq9M5MKtlSRmuUQyz1fE0tz9OEdJFDgwjJghdvXZbQqGVLKgCvJ+wcB20pD/2HBOdisKhlmY9mfgwRIkxfnbCsOnClsmSVvbOUZrtd5866e4zeENYTbqeSBROLWmwSCPFG6GHoBMQUvAEX+OYp5UiAW4Qnw17AbmDZkCSOmQayMQ2B/gFhAscmFYcnrxQ0dbk+FhKTxrmCPrYV7+Ij6n45ymEMbO1v9Q+XXVPB40NqbDV89WkRhZzE9FJeKBwah35Dh2yy7BWnGuLkoise+F2Umjqibm0a8fai9NRDHuGyaNIV9d9PkUN04uDqDaEOv5B8vJqi76a0uKoVJMMplvk5gtJx+DM7Y1qE6RSjizAfUf+q4AYRsqWkISIv24IQvtTC19vr9Y1NRvT7VflA8f/ufQzd/nSoqjUSBekD7r/Fa9EAkVSh2t+OPJq1huOdjImcj/5Z67IbvK7IH5CffY4yM6t2ORylD5Fkc5VTBysINT3g4rhlTcRz+V012wbEngymdcFCYawHQ9a87Ea9/6BLMOrmHN3cyXObENgrE7qG8sXaCbrjEA9xr0z4nvvRxma65I+NnPog="
  file_glob: true
  file: artifacts/*
  skip_cleanup: true
  on:
    repo: artcom/topic-browser
    tags: true
