language: node_js
node_js:
- 10.12.0
script: npm run release
deploy:
  provider: releases
  api_key:
    secure: "cYpVAmWzDwKTwpbUIB2saDd9CSvWH/yM2UyPaqqGqUmfvsbd4U0arzy9mCWOc8lotu6jjV8NS73pksD0kbLnbqeNIgRAHL2mJh9CDfWbPT/78dY7kB+sifbSkWq7bDIJGF3x5NMekelQJJ9zEg8Wm3uFORGzuYNb0GbGpwSdU/rErMWPZkHP4oMsD8TwV9RIwZQnmUJ6g/aWivELgxmc8kMDIyYHAA82bkMhp6elw1ABz0+gJArMsS39+XWJA/EACQE23dbm2cCkfCGbaeYd5WcwXx7D6EpR0B49GHvNReUgBXXftIi+TrHjjScINZuOEGO/kI6hj31AcVKxsFBqeSLuJM/SwwoNQ+vykAKi3Y8YZoxyl/vVmEBma0ZPNdVNBXKKM+PUYuj3sr9FSYTkY9YBqtAFErRa21ns6r8xRLof4wE0rEJsIvVgHSPSm1BqI/xka5aAaUHhLrEnHDPm+hHcj1WkLu9voIlN/lGXDnIohCtVV8mX9GX3WC+Rs701Z9TQlaKco+rrQCCww6UFE79EWZ0wQH8vUU+tOq6YPokRHQ48LD9W/32gk/7vQiWtqC8CqwqagPcZxOEmt7NaEjbctCKTqAxzBrV8DLTQA+EFZelqq9fdsJnEP0syXtNn4E0F/JkMeB8+wv/McUB2tVoc3P5pECGs/c5OaSRiabI="
  file_glob: true
  file: artifacts/*
  skip_cleanup: true
  on:
    repo: artcom/topic-browser
    tags: true
