#!/bin/bash

set -eo pipefail

PUBLIC_DIR="public"
ARTIFACTS_DIR="artifacts"

echo "Building"
npm run build

echo "Packaging"
mkdir "${ARTIFACTS_DIR}"
cd "${PUBLIC_DIR}"
echo {\"branch\": \"$TRAVIS_BRANCH\", \"commit\": \"$TRAVIS_COMMIT\", \"build\": $TRAVIS_BUILD_NUMBER} > build.json
zip -r -9 "../${ARTIFACTS_DIR}/topic-browser-${TRAVIS_BRANCH}.zip" *
tar czvf "../${ARTIFACTS_DIR}/topic-browser-${TRAVIS_BRANCH}.tar.gz" *
