export const REQUEST_TOPIC = "REQUEST_TOPIC"
export const UPDATE_TOPIC = "UPDATE_TOPIC"

export const DELETE_TOPIC = "DELETE_TOPIC"
export const CANCEL_TOPIC_DELETION = "CANCEL_TOPIC_DELETION"

export const CREATE_TOPIC = "CREATE_TOPIC"
export const CANCEL_TOPIC_CREATION = "CANCEL_TOPIC_CREATION"

export const EDIT_PAYLOAD = "EDIT_PAYLOAD"
export const CANCEL_PAYLOAD_EDITING = "CANCEL_PAYLOAD_EDITING"

export const START_TOPIC_DELETION = "START_TOPIC_DELETION"
export const FINISH_TOPIC_DELETION = "FINISH_TOPIC_DELETION"

export const START_TOPIC_PUBLICATION = "START_TOPIC_PUBLICATION"
export const FINISH_TOPIC_PUBLICATION = "FINISH_TOPIC_PUBLICATION"
